--Em banco para os oculos, terei 3 listas - Fem / Masc / Unissex
INSERT INTO TB_OCULOS_LIST (NAME) VALUES ('FEMININO');  --LISTA 1
INSERT INTO TB_OCULOS_LIST (NAME) VALUES ('MASCULINO'); --LISTA 2
INSERT INTO TB_OCULOS_LIST (NAME) VALUES ('UNISSEX');   --LISTA 3

--Alimentando a tabela oculos no banco - 15 itens
--Alimentando a tabela oculos no banco - 5 itens para cada genero
--Lista - 1: Feminino
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Portal X', 2025, 'Feminino', 4.8,'https://www.oakley.com/pt-br/product/W0OO9460?variant=888392641999','Com linhas angulares e aerodinâmicas, o Flux Vector combina leveza e firmeza para o uso esportivo.','Feito em O-Matter™ de alta resistência, possui hastes ventiladas para melhor fluxo de ar e conforto prolongado. As lentes com tecnologia Prizm™ Road otimizam o contraste e a visibilidade em ambientes urbanos e rodovias.',899.90, 320.95);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Radar EV Advancer', 2025, 'Feminino', 4.9, 'https://www.oakley.com/pt-br/product/W0OO9442?variant=888392642120', 'Design leve e elegante para quem busca estilo e performance.', 'As lentes arredondadas com Prizm™ Black Polarized reduzem o brilho e realçam os tons naturais. Ideal para o dia a dia, o Lyra Edge combina sofisticação e tecnologia com um ajuste preciso e confortável.',2016.00, 611.17);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Frogskins MIX', 2024, 'Feminino', 4.7, 'https://www.oakley.com/pt-br/product/W0OO9428?variant=888392640512', 'Inspirado em terrenos acidentados e aventuras outdoor, o Terraform entrega robustez e estilo moderno.','A estrutura reforçada garante durabilidade extrema. O encaixe anatômico e as lentes Prizm™ Trail oferecem nitidez superior em ambientes naturais e trilhas.',550.00, 216.90);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Tailend TI', 2025, 'Feminino', 5.0,'https://www.oakley.com/pt-br/product/W0OO6026?variant=888392674975', 'Agradável aos olhos, com um toque leve. Conheça o Tailend TI: o icônico modelo Tailend, reinventado. Sua estrutura de titânio sem aro faz você sentir como se ele fosse quase leve, mas cara, ele é muito pesado em estilo.', 'Agradável aos olhos, com um toque leve. Conheça o Tailend TI: o icônico modelo Tailend, reinventado. Sua estrutura de titânio sem aro faz você sentir como se ele fosse quase leve, mas cara, ele é muito pesado em estilo.', 2200.00, 1500.00);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Permian', 2024, 'Feminino', 4.5, 'https://www.oakley.com/pt-br/product/W0OO9520?variant=888392675996', 'Eleve seu visual com um toque de requinte. Inspirado nos looks fora de campo dos principais atletas, o Permian é uma peça de destaque com uma armação elegante e lentes de base bases para o ajuste e conforto máximos.', 'Eleve seu visual com um toque de requinte. Inspirado nos looks fora de campo dos principais atletas, o Permian é uma peça de destaque com uma armação elegante e lentes de base bases para o ajuste e conforto máximos, Armação de O-Matter, Design Envolvente e Logotipo OAKLEY Fractal', 1100.00, 850.00);
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Lista - 2: Masculino
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Kato', 2025, 'Masculino', 5.0, 'https://www.oakley.com/pt-br/product/W0OO9455?variant=888392643205', 'Modelo esportivo de alto desempenho com design envolvente.', 'A curvatura ampla proporciona cobertura total e estabilidade durante o movimento. As lentes Prizm™ Sapphire garantem proteção total contra UV e visão impecável mesmo sob sol intenso.',999.00, 411.40);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Gibston', 2025, 'Masculino', 4.6, 'https://www.oakley.com/pt-br/product/W0OO9449?variant=888392640732', 'Design ultraleve inspirado em correntes de ar e fluidez.', 'As hastes finas e flexíveis em O-Matter™ proporcionam conforto durante todo o dia. Lentes Prizm™ Rose Gold aprimoram os detalhes e realçam cores quentes em ambientes urbanos e naturais.',791.00, 282.30);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Holbrook XL', 2023, 'Masculino', 4.5, 'https://www.oakley.com/pt-br/product/W0OO9417?variant=888392639988', 'Um clássico reinterpretado com tecnologia moderna.', 'Com estrutura reforçada e ponte ajustável em três níveis, o Spectrum RX é compatível com lentes de grau e oferece transição perfeita entre estilo de rua e esportividade.',560.00, 199.90);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Plantaris Polaris Collection', 2025, 'Masculino', 5.0, 'https://www.oakley.com/pt-br/product/W0OO9437PSC?variant=888392675040', 'Polaris é a Estrela do Norte que você pode seguir para expressar sua personalidade única, com a confiança de avançar para uma nova fronteira. A coleção sob medida da Oakley apresenta novos tratamentos de pintura Abyss Galaxy e Fern Galaxy.', 'Inspirado pela observação das formas e criaturas encontradas na natureza, o Plantaris tem um design ousado com características funcionais e técnicas. O design de haste ajustável se divide em duas bases inspiradas em sapos, cobertas por pontas de silicone transparentes exibindo o núcleo de arame que remete a veias. Uma ponta cônica removível torna-o adaptável ao humor e ao ambiente em que você estiver, enquanto a tecnologia Switchlock facilita a troca das lentes. Para cores e contrastes aprimorados em todos os lugares que você vai, a Tecnologia de Lentes Prizm™ fornece os detalhes.', 1700.00, 950.00);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley X Satisfy Stunt Devil', 2025, 'Masclino', 5.0, 'https://www.oakley.com/pt-br/product/W0OO9517STY?variant=888392682956', 'Stunt Devil é o melhor modelo de óculos esportivo, proporcionando retenção, aderência e conforto sobrenaturais em cada salto e corrida.', 'Stunt Devil é o melhor modelo de óculos esportivo, proporcionando retenção, aderência e conforto sobrenaturais em cada salto e corrida. Trabalhando ao lado da Satisfy® Running, essas iterações únicas combinam tecnologia revolucionária e estética distinta, permitindo que os usuários se aventurem fora do caminho tradicional.', 1500.00, 900.00);
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Lista - 3: Unissex
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Pitchman R', 2025, 'Unissex', 4.9, 'https://www.oakley.com/pt-br/product/W0OO9439?variant=888392640899', 'Inspirado nas cores do cosmos e na velocidade da luz.', 'Com lentes espelhadas Iridium™ e design geométrico futurista, o Nebula Shift combina performance e atitude. Ideal para quem busca diferenciação e proteção de alto nível.',1150.00, 410.60);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Forager', 2024, 'Unissex', 4.7, 'https://www.oakley.com/pt-br/product/W0OO9421?variant=888392641554', 'Minimalista e resistente, o Crux Zero oferece o equilíbrio perfeito entre leveza e estrutura.', 'As hastes de titânio escovado proporcionam conforto e rigidez. As lentes Prizm™ Deep Water reduzem reflexos e aumentam a clareza visual em ambientes náuticos.',350.00, 124.90);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('HSTN - Frame', 2025, 'Unissex', 4.8, 'https://www.oakley.com/pt-br/product/W0OX8139?variant=888392604743', 'Com curvas suaves e acabamento translúcido, o Solaris Frame expressa leveza e autenticidade.', 'A lente Prizm™ Bronze aumenta o contraste e valoriza tons terrosos. Perfeito para uso urbano, o modelo alia moda e tecnologia em um só design.',1050.00, 410.60);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Sutro S', 2025, 'Unissex', 5.0, 'https://www.oakley.com/pt-br/product/W0OO9462?variant=888392643740', 'Design futurista inspirado no universo digital.', 'As linhas retas e a moldura em acetato reforçado garantem um visual moderno e marcante. Com lentes Prizm™ Black, o Cyberline entrega nitidez e conforto visual em qualquer ambiente.', 1050.00, 410.60);
INSERT INTO tb_oculos (name, oculos_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('De Soto Polaris', 2024, 'Unissex', 5.0, 'https://www.oakley.com/pt-br/product/W0OO9494PSC?variant=888392675071' , 'Polaris é a Estrela do Norte que você pode seguir para expressar sua personalidade única, com a confiança de avançar para uma nova fronteira.', 'Esteja pronto para o carpete vermelho com o De Soto, um óculos de sol arrojado impulsionado por um design igualmente arrojado. Parte da Coleção Players, o De Soto foi inspirado nas silhuetas dos anos 60, com um toque novo e distinto da Oakley®. Com uma lente dupla espessa e marcante, material de armação O Matter™ durável e leve e o exclusivo logotipo Oakley® Fractal na haste, o De Soto oferece estilo infinito para aquela foto pré-jogo ou comemoração pós-jogo. Equipado com a Tecnologia de Lentes Prizm™ que realça cores e contraste, o De Soto vem com microbag e caixa personalizadas.', 960.00, 350.50 );
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Alimentando a tabela que pertence o id do oculos, a lista e a posicao que ele pertence
--Lista - 1: Feminino
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (1, 5, 4);
------------------------------------------------------------------------------------------------
--Lista - 2: Masculino
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (2, 10, 4);
------------------------------------------------------------------------------------------------
--Lista - 3: Unissex
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (3, 11, 0);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (3, 12, 1);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (3, 13, 2);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (3, 14, 4);
INSERT INTO tb_belonging (list_id, oculos_id, position) VALUES (3, 15, 5);

--Alimentando a tabela tenis no banco - 10 itens
--Em banco para os tenis, terei 2 listas - Fem / Masc
-- INSERT INTO TB_SHOES_LIST (NAME) VALUES ('FEMININO');  --LISTA 1
-- INSERT INTO TB_SHOES_LIST (NAME) VALUES ('MASCULINO'); --LISTA 2
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES (' Oakley Airstrip', 2024, 'Masculino', 5.0,'https://static.netshoes.com.br/produtos/tenis-oakley-air-strip-wt25-masculino/02/PFO-1661-002/PFO-1661-002_zoom1.jpg?ts=1760758803&ims=1088x','É a mais recente adição à nossa icônica família Teeth. Esta releitura apresenta um toque de sofisticação com seu acabamento em PU de alta qualidade, e o logo em metal acrescenta um toque de rubustez ao design.','O AIRSTRIP mantém a tradição de durabilidade e estilo que a família Teeth é conhecida por, enquanto adiciona um toque moderno e agressivo. Ele é a escolha perfeita para aqueles que desejam se destacar com um visual único e contemporâneo. Características Principais: Composição: 100% PU. Garantia conta defeito de fabricação.',1190.90, 320.95);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Mod Slip-On Teeth Og Piet', 2024, 'Masculino', 4.5, 'https://www.oakley.com/pt-br/product/FOF100602?variant=8056153538695', 'O Tenis Oakley Teeth Slip-on, originalmente lançado nos anos 2000, é talvez a versão menos conhecida da familia Teeth.', 'Pertencente a colaboração entre a Oakley e Piet, umas das marcas mais icônicas no streetwear, o modelo TEETH SLIPON PIET é uma releitura que possui um solado de borracha garantindo máxima durabilidade e resistência a abrasão, a entressola em EVA proporciona maior conforto. Seu logotipo da Oakley em metal com logo ellipse em marcação na parte frontal do modelo revela a robustez do produto e estilo único.', 750.00, 285.50);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('FLAK III', 2024, 'Masculino', 5.0,'https://www.oakley.com/pt-br/product/FOF100575?variant=8056153491563&size42', 'O tênis Flak III faz parte da linha Outdoor da Oakley e foi pensado a fim de unir conforto e estilo em um calçado diferenciado.', 'Pertencente a linha Outdoor, o modelo FLAK III possui um solado de borracha garantindo máxima durabilidade e resistência a abrasão, a entressola em EVA proporciona maior conforto, parte superior em couro e logotipo da marca em metal revelam a robustez do produto e garantem durabilidade.', 720.00, 350.50 );
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Flak II SNKR', 2001, 'Masculino', 3.5, 'https://www.oakley.com/pt-br/product/FOF100437?variant=193517803452', 'Pertencente a linha casual, o modelo FLAK II SNKR é a releitura do modelo mais icônico da marca de forma ainda mais confortável e versátil.', 'Possui o solado Diamond inspirado em cristais raros com visual robusto, versátil e premium, em EVA para conforto superior. Borracha ao longo de toda extensão do solado, garante durabilidade e tração. Camurça e mesh na parte superior e logo em metal garantem durabilidade, ventilação e autenticidade ao modelo.', 799.00, 550.00);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Airstrip Leather', 2023, 'Masculino', 4.0, 'https://www.oakley.com/pt-br/product/FOF100667?variant=8056153745574', 'O Airstrip Leather combina sofisticação e durabilidade com seu elegante design em couro. Confeccionado com materiais de alta qualidade, oferece conforto e um ajuste perfeito para o uso diário.', 'O Airstrip Leather combina sofisticação e durabilidade com seu elegante design em couro. Confeccionado com materiais de alta qualidade, oferece conforto e um ajuste perfeito para o uso diário. Seu visual clássico e moderno, acentuado pelo acabamento em couro, faz dele uma escolha versátil e estilosa para qualquer ocasião. Além disso, o Airstrip Leather celebra a herança da Oakley com um design genuíno que reflete a essência e a identidade única da marca.', 1499.90, 850.00);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Claws', 2025, 'Feminino', 4.0, 'https://www.oakley.com/pt-br/product/WFOF100613?variant=8056153688543', 'O modelo CLAWS surge para referenciar os clássicos tênis de skate dos anos 90, com uma aparência robusta e cheia de estilo.', 'O modelo CLAWS surge para referenciar os clássicos tênis de skate dos anos 90, com uma aparência robusta e cheia de estilo. Feito principalmente de camurça, oferece durabilidade e um visual vintage autêntico. O forro de espuma proporciona conforto excepcional, ideal para uso prolongado. Destacando-se pela presença da Ellipse de metal na lateral, este tênis afirma a identidade marcante da Oakley. Seu solado, combinando EVA e borracha ao longo da parte inferior, oferece tração e estabilidade, garantindo conforto e segurança em todas as atividades do dia a dia.', 650.00, 300.00);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Tênis Oakley Masculino Battle', 2022, 'Feminino', 3.0,'https://www.netshoes.com.br/p/tenis-oakley-masculino-battle-PFO-1025-006', 'O Tênis Battle faz parte da linha Outdoor da Oakley, é perfeito para quem procura um calçado robusto e versátil para o dia a dia.', 'O Tênis Battle faz parte da linha Outdoor da Oakley, é perfeito para quem procura um calçado robusto e versátil para o dia a dia. Seu cabedal é confeccionado em material resistente e mesh, com o detalhe do logo em metal, proporcionando firmeza e durabilidade. Possui forro acolchoado que oferece muito conforto durante todo o uso. O puxador no calcanhar, facilita o calce e sua palmilha macia garante uma sensação agradável ao caminhar. A entressola em EVA proporciona leve amortecimento e estabilidade, enquanto o solado de borracha garante aderência e resistência à abrasão. Adquira já o seu!', 540.00, 299.50);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Flak III Frog Edição Limitada ', 2024, 'Feminino', 4.5, 'https://www.netshoes.com.br/p/tenis-masculino-oakley-flak-iii-frog-edicao-limitada-PFO-0535-006', 'Tênis Oakley Flak III Frog Original O Tênis Oakley Flak III Frog é perfeito para os amantes de aventuras ao ar livre.', 'Tênis Oakley Flak III Frog Original O Tênis Oakley Flak III Frog é perfeito para os amantes de aventuras ao ar livre. Pertencente a linha Outdoor, o modelo Flak III Frog possui um solado de borracha garantindo máxima durabilidade e resistência a abrasão, e a entressola de EVA proporcionando maior conforto.', 899.00, 450.00);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Masculino Mod Modoc Low II', 2020, 'Feminino', 4.0, 'https://www.netshoes.com.br/p/tenis-oakley-masculino-mod-modoc-low-ii-camo-38-grafite-PFN-6992-266', 'A Oakley apresenta a você um dos seus modelo mais esperado do ano, o Modoc Low II, Ele possui o cabedal construído em camurça com partes em matérias sintéticos com logotipo da marca em metal e deta', 'Para você que busca algo estiloso e perfeito para os dias de aventura, o Tênis Oakley Modoc Low II é ideal. O cabedal (parte superior do calçado) em têxtil, sintético e camurça, com solado em borracha tratorada. O tênis masculino conta com forro têxtil e reforço acolchoado proporcionando mais proteção.', 470.00, 250.00);
INSERT INTO tb_shoes (model_name, shoes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Stratus Skull', 2024, 'Feminino', 2.5, 'https://www.netshoes.com.br/p/tenis-oakley-stratus-skull-masculino-PFN-9690-006', 'Possui forma pequena, para um melhor ajuste nos pés, recomendamos a compra de um tamanho maior do que o seu usual.', 'Design robusto e estiloso para o dia a dia. O tênis masculino Oakley Stratus recebe cabedal em material resistente que proprociona firmeza e durabilidade, opção versátil para te acompanhar em diversos momentos. Além disso, conta com forro levemente acolchoado, tira de calce fácil e palmilha macia que eleva a sensação de conforto.', 350.00, 180.50);


--Alimentando a tabela backpacks no banco - 10 itens
--Em banco para os backpacks, terei 3 listas - Fem / Masc / Unissex
--INSERT INTO TB_BACK_PACK_LIST (NAME) VALUES ('FEMININO');
--INSERT INTO TB_BACK_PACK_LIST (NAME) VALUES ('MASCULINO');
--INSERT INTO TB_BACK_PACK_LIST (NAME) VALUES ('UNISSEX');
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Mochila Kitchen Sink', 2020, 'Unissex', 5.0, 'https://www.oakley.com/pt-br/product/92060A?variant=8056153725835', 'Um compartimento principal com abertura superior oferece armazenamento robusto, estilo mochila, enquanto bolsos internos e externos especializados organizam itens como calçados, laptops e óculos', 'Mochila Oakley com compartimento com acesso lateral para notebook de até 17”, compartimento para calçados, painel organizador interno, bolso forrado para proteger óculos/media Pocket, matéria-prima de alta resistência, peças em metal com Oakley DNA, ajustadores laterais e espuma nas costas e nas alças para maior conforto.', 2200.00, 1450.00);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Bathroom Sink Rc Backpack', 2023, 'Unissex', 5.0, 'https://www.oakley.com/pt-br/product/FOS901477?variant=8056153248457', 'Totalmente robusto. Ultra-resistente. Embalado com todos os compartimentos, mangas, zíperes e bolsos que você precisa para aventuras em trilhas.', 'A versão menor da nossa mochila Kitchen Sink mais vendido, a mochila Bathroom Sink RC apresenta o mesmo exterior Cordura durável e acabamento destacado, em um tamanho ideal para as missões diárias. Essa mochila começa no compartimento principal com uma entrada lateral com zíper e uma capa interna acolchoada que acomoda um laptop de 15 polegadas. Dentro, você encontrará vários bolsos para cada pequena coisa, incluindo um estojo rígido para manter os óculos seguros. Do lado de fora, há uma alça de compressão para prender as coisas, alças acolchoadas com fivela para conforto durante todo o dia. Finalmente, a Bathroom Sink RC Backpack é grande em estilo: detalhes e acabamentos em metal, um logotipo metálico da Oakley e cores ousadas para uma perfeição de armazenamento.', 1999.90, 11250.50);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Latitude Flex Pack', 2020, 'Unissex', 3.25, 'https://www.oakley.com/pt-br/product/FOS901676?variant=8056153604956', 'The Latitude Flex Pack is ready for wherever you roam.', 'Made with 100% recycled polyester and ultra-rugged Cordura material, it’s water-repellent, weather-tough, and packed with pockets to keep you organized on the road. The main compartment features an adjustable drawcord and Fidlock ™ magnetic clips for easy open and close, while multiple external pockets let you stash every little thing. Delight in details like a modular and detachable external cargo pocket, plus removable shoulder straps, padded handles, and a chest strap (with Fidlock ™ clips) for any and every carry option. Have bag, will travel.', 3.300, 1250.90);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Urban Ruck Rc Duffle', 2024, 'Unissex',4.85, 'https://www.oakley.com/pt-br/product/FOS901048?variant=8056153280600', 'Mala Oakley com alças acolchoadas para carregar em mãos.', 'Mala Oakley com alças acolchoadas para carregar em mãos, alça personalizada e acolchoada para carregar no ombro, grande abertura principal com zíper personalizado, bolsos organizdores externos personalizados na parte frontal ,logo Elipse em metal, logo em relevo na parte superior, bolso lateral individual com respiros, forro personalizado, zíperes externos personalizados, tecido ripstop, fundo reforçado e etiquetas personalizadas.',1550.00, 850.00);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Urban Path Rc 25L Backpack', 2022, 'Masculino', 3.25, 'https://www.oakley.com/pt-br/product/FOS901337?variant=8056153602808', 'Multifuncional. Pronto para viagens. Feito para enfrentar a vida diária e a aventura total. A mochila Urban Path RC 25L é feita de tecido de cordura 100% reciclado, uma escolha durável e resistente à água para manter sua carga seca e pronta para uso.', 'Cheia de detalhes cuidadosos e recursos de alto desempenho, esta mochila multifuncional tem bolsos para dias úteis: um bolso frontal com zíper para acesso rápido, uma capa acolchoada para laptop e tablet e até uma bolsa dedicada aos óculos, completa com forro de microfibra e zíper. Bolsos laterais de malha feitos para garrafas de água de fácil acesso e alças confortáveis ​​no topo. Cores inspiradas na terra para uma peça robusta e multifuncional que você usará todos os dias.', 770.00, 345.50);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Road Trip Terrain 25L Rc Pack', 2019, 'Masculino', 3.5,'https://www.oakley.com/pt-br/product/FOS901338?variant=193517925611', 'A mochila Oakley Road Trip Terrain 25L RC Pack é a escolha definitiva. Ela foi projetada com armazenamento modular para manter seus pertences organizados e equilibrados para aventuras próximas e distantes.', 'Fabricado com material 100% reciclado, resistente à água e equipado com zíper impermeável na frente, compartimento específico para laptop, forro de malha respirável na parte traseira e painel inferior reforçado para suportar tudo o que você precisa em movimento. Adicione uma aba enrolável para expandi-lo e comprimi-lo, um bolso forrado de microfibra e alças de suporte personalizáveis, você estará pronto para alcançar novos patamares.', 1390.00, 750.00);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Mochila Enduro 3.0 Big Backpack', 2017, 'Masculino', 4.1,'https://m.media-amazon.com/images/I/91GGEAwRQlL._AC_SX569_.jpg','A mochila grande Enduro 3.0 atende às suas necessidades diárias de excursão.', 'Um exterior resistente com revestimento repelente de água, juntamente com bolsos acolchoados para laptop e tablet e painel interno organizacional mantém o equipamento organizado e seguro, enquanto o bolso externo para óculos permite o armazenamento rápido de suas persianas. A malha respirável no painel traseiro proporciona conforto durante todo o dia, e a correia Jacquard com um puxador de marca completa o que certamente será um companheiro digno de trilha.', 710.00, 299.00);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Mochila Mochila Enduro 30l 2.0', 2017, 'Feminino', 4.5, 'https://m.media-amazon.com/images/I/71OJHi9CtEL._AC_SX569_.jpg', 'O pacote Enduro 30 foi projetado para oferecer armazenamento espaçoso e especializado para eletrônicos e equipamentos quando você estiver em movimento.', 'Oferece alta visibilidade em condições de pouca luz para dar a você mais segurança.', 650.00, 245.90);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('The Freshman Skate Backpack', 2022, 'Feminino', 3.1, 'https://www.oakley.com/pt-br/product/FOS901202?variant=8056153442886', 'Ir do ponto “A” ao ponto “B” ficou mais fácil graças à prática Mochila Freshman Skate.', 'O tecido resistente e impermeável protege seus pertences e mantém as intempéries fora do caminho, enquanto o painel traseiro moldado em malha estruturada oferece conforto ergonômico em diversas atividades. O acabamento traz vários bolsos seguros e um prático sistema para guardar seus óculos de sol.', 625.00, 440.00);
INSERT INTO tb_backpack (model_name, backpack_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('The Freshman Packable', 2.0, 'Feminino', 3.0, 'https://www.oakley.com/pt-br/product/FOS901204?variant=193517735357', 'Para deslocamentos fáceis para a escola, biblioteca ou apenas um passeio, a mochila Freshman Pkble RC oferece conveniência total e funcionalidade moderna.', 'Para deslocamentos fáceis para a escola, biblioteca ou apenas um passeio, a mochila Freshman Pkble RC oferece conveniência total e funcionalidade moderna. O design compactável oferece excelente portabilidade quando é hora de reduzir o tamanho, e um exterior resistente e resistente à água fornece proteção adicional para seu equipamento. Os bolsos internos protegem os itens essenciais e é finalizado com alças de ombro de malha acolchoadas ajustáveis ​​para respirabilidade e conforto.', 340.00, 150.00);

--Alimentando a tabela clothes no banco - 10 itens
--Em banco para os backpacks, terei 2 listas - Fem / Masc
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Latitude Flex Tech Jacket', 2025, 'Masculino', 5.0, 'https://www.oakley.com/en-us/product/FOA406151?variant=8056153422116', 'Meet your new go-to for gym-to-work, work-to-play, and everything in between.', 'This insulated, laminated corduroy jacket is the perfect waterproof barrier between you and the rain, wind, and cold. Fully taped seams keep moisture out, while cinchable elastic at the hood and hem let you customize the fit when the weather kicks up. Zippable side vents with mesh inserts let you cool down when you need it; lycra cuffs with thumb holes help keep your hands warm. Pockets in the front and the back let stash stuff on the go. Push your performance with a slim, moves-with-you fit.', 1750.00, 900.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Sub Temp RC Gore-Tex Jacket 2.0', 2025, 'Masculino', 5.0, 'https://www.oakley.com/en-us/product/FOA406100?variant=8056153429023', 'Our men’s Sub Temp RC Gore-tex® Jacket 2.0 is warm, waterproof and windproof, so you can get the most out of the outdoors.', 'Its 2L stretch Gore-tex® material is a breathable barrier between you and the elements, while Hydrofree DWR treatment prevents water absorption (no cold, clammy skin – even on storm days). This all-mountain jacket is insulated for extra cozy on colder days, with pit vents to get air flowing. A removable snow skirt lets you customize it from groomer days to deep snow, and includes both a RECCO tech reflector for searchability and an RFID pass pocket to quick access to the lifts.', 2550.00, 1750.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Snowbound Pkble Down Puffy Jacket', 2025, 'Masculino', 5.0, 'https://www.oakley.com/en-us/product/FOA404730?variant=193517880330', 'Winter-ready. Rarefied warmth. The Snowbound Packable Down Puffy Jacket is a cold-weather staple for everyday comfort, functional layering and suitcase-stuffing.', 'The jacket’s outside is treated with our O Protect DWR to keep you dry on stormy days. The inside’s packed with details to keep you ready for adventure. From a mesh-lined pocket for wet mitts to side zip pockets for keys and phone, a packable pocket and more internal spots with mesh, this puffy’s made for cold temps and full days.', 1850.00, 680.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Range RC Jacket 2.0', 2025, 'Masculino', 4.75, 'https://www.oakley.com/en-us/product/FOA406098?variant=8056153725071', 'Shop online, same-day pickup at Oakley and Sunglass Hut stores, subject to product availability.', 'Own the park. Win the day. Our men’s Range RC Jacket 2.0 features a roomier fit so you can hit every jump with full freedom of movement, plus warm, breathable comfort from your first run to your last. Insulated and treated with FN DRY ™ 10K/10K, it’s made to let heat and sweat escape while providing a barrier against the elements on winter days.', 1580.00, 750.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Latitude Flex Baselayer', 2024, 'Masculino', 3.25, 'https://www.oakley.com/en-us/product/FOA406148?variant=8056153439213', 'The men’s Latitude Flex Base Layer keeps you warm – without losing high-performance function', 'Made with a merino blend and featuring a built-in balaclava (plus thumbholes to boot), this close-fitting pullover is the perfect base layer or standalone top for winter training. We added a front chest panel with wind-blocking fabric for more protection, and used a flatlock stitch throughout to reduce bulk (and eliminate chafing).', 950.00, 125.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Relax Crew Sweatshirt 2.0', 2022, 'Feminino', 4.0, 'https://www.oakley.com/en-us/product/FOA404846?variant=8056153601979', 'Out-of-office mode, in a top. The men’s Relax Crew Sweatshirt is a brushed-cotton dream made in part with recycled materials for a feel-good pullover that looks good, too.', 'A ribbed crew with ribbed cuffs and hem, it’s a cozy, do-everything sweat that comes in four fresh colors. Mix and match with our Relax Short 2.0, polo or jogger for a clean, on-trend style. All comfort. In one, put-together piece.', 400.00, 150.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Wmns Tnp Tbt Insulated Jacket', 2025, 'Feminino', 5.0, 'https://www.oakley.com/en-us/product/FOA500472?variant=193517911010', 'The TNP TBT Insulated Jacket brings warmth, function and style to colder conditions.', 'Designed with technical features like critically taped seams to help retain heat and a 3-point adjustable, helmet-compatible hood for more protection against wintry weather.', 2030.00, 1100.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Performance LS Rashguard', 2022,'Feminino', 4.3, 'https://www.oakley.com/en-us/product/FOA406861?variant=8056153597401', 'Hit the waves with even more confidence in this rash guard constructed from a flexible and moisture-wicking recycled nylon and spandex blend designed not only to protect your skin from the sun and other irritants but also to keep you warm and dry in and out of the water.', 'From the laser-cut ventilation holes to the double layer cuffs with thumbholes and the bottom hem with elastic loop to connect to your board shorts, every detail is engineered to maximize comfort and keep you at the top of your game. Turtleneck collar with 3D logo on chest and left sleeve.', 500.00, 125.00);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Oakley Resist Jacquard', 2020, 'Feminino', 2.5, 'https://www.oakley.com/en-us/product/FOA406809?variant=8056153578523', 'Sporting a highly original yet understated all-over pattern, this polo shirt, available in six colors, is made from a four-way stretch fabric blend that ensures optimal fit and comfort as you go about getting your handicap down.', 'The fastening consists of three recycled buttons while additional details include the underarm gusset and the hidden yet highly practical eyewear loop on the placket, a boon for all keen golfers. Modern fit with the Ellipse logo decorating the left sleeve.', 600.00, 125.50);
INSERT INTO tb_clothes (name, clothes_year, genre, review_score, img_url, short_description, long_description, price, cost_price) VALUES ('Latitude Flight Tee', 2019, 'Feminino', 3.55,'https://www.oakley.com/en-us/product/FOA406825?variant=8056153591553', 'This multi-purpose plain t-shirt is a must-have staple for your wardrobe, perfect as-is or as a base layer under a sweater or jacket.', ' Made from breathable and elastic cotton and elastane, it features a classic ribbed collar with the hallmark Oakley eyewear leash on the back and a convenient hidden zip pocket at the side for small valuables you want to keep close to your chest. Other notable details include the shoulder seam with reflective tape and the reflective Oakley Ellipse logo on the back. Two versatile color options.', 650.00, 125.50);
